source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UniversalPicker_Example', :exclusive => true do
  pod "UniversalPicker", :path => "../"
end

target 'UniversalPicker_Tests', :exclusive => true do
  pod "UniversalPicker", :path => "../"

  
end
